# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/mazola/Desktop/Projet3/tp1.cache/wt [current_project]
set_property parent.project_path C:/Users/mazola/Desktop/Projet3/tp1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files C:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/BD_tp1.bd
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/ip/BD_tp1_processing_system7_0_0/BD_tp1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/ip/BD_tp1_axi_gpio_0_0/BD_tp1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/ip/BD_tp1_axi_gpio_0_0/BD_tp1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/ip/BD_tp1_axi_gpio_0_0/BD_tp1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/ip/BD_tp1_rst_processing_system7_0_100M_0/BD_tp1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/ip/BD_tp1_rst_processing_system7_0_100M_0/BD_tp1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/ip/BD_tp1_rst_processing_system7_0_100M_0/BD_tp1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/ip/BD_tp1_auto_pc_0/BD_tp1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/BD_tp1_ooc.xdc]
set_property is_locked true [get_files C:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/BD_tp1.bd]

read_verilog -library xil_defaultlib C:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/hdl/BD_tp1_wrapper.v
read_xdc C:/Users/mazola/Desktop/Projet3/tp1.srcs/constrs_1/new/contraintsTP1.xdc
set_property used_in_implementation false [get_files C:/Users/mazola/Desktop/Projet3/tp1.srcs/constrs_1/new/contraintsTP1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top BD_tp1_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef BD_tp1_wrapper.dcp
catch { report_utilization -file BD_tp1_wrapper_utilization_synth.rpt -pb BD_tp1_wrapper_utilization_synth.pb }
