# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/contraintsTP1.xdc

# Block Designs: bd/BD_tp1/BD_tp1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_tp1 || ORIG_REF_NAME==BD_tp1}]

# IP: bd/BD_tp1/ip/BD_tp1_processing_system7_0_0/BD_tp1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_tp1_processing_system7_0_0 || ORIG_REF_NAME==BD_tp1_processing_system7_0_0}]

# IP: bd/BD_tp1/ip/BD_tp1_axi_gpio_0_0/BD_tp1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_tp1_axi_gpio_0_0 || ORIG_REF_NAME==BD_tp1_axi_gpio_0_0}]

# IP: bd/BD_tp1/ip/BD_tp1_processing_system7_0_axi_periph_0/BD_tp1_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_tp1_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==BD_tp1_processing_system7_0_axi_periph_0}]

# IP: bd/BD_tp1/ip/BD_tp1_rst_processing_system7_0_100M_0/BD_tp1_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_tp1_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==BD_tp1_rst_processing_system7_0_100M_0}]

# IP: bd/BD_tp1/ip/BD_tp1_auto_pc_0/BD_tp1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_tp1_auto_pc_0 || ORIG_REF_NAME==BD_tp1_auto_pc_0}]

# XDC: bd/BD_tp1/ip/BD_tp1_processing_system7_0_0/BD_tp1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_tp1_processing_system7_0_0 || ORIG_REF_NAME==BD_tp1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/BD_tp1/ip/BD_tp1_axi_gpio_0_0/BD_tp1_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_tp1_axi_gpio_0_0 || ORIG_REF_NAME==BD_tp1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/BD_tp1/ip/BD_tp1_axi_gpio_0_0/BD_tp1_axi_gpio_0_0_ooc.xdc

# XDC: bd/BD_tp1/ip/BD_tp1_axi_gpio_0_0/BD_tp1_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BD_tp1_axi_gpio_0_0 || ORIG_REF_NAME==BD_tp1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/BD_tp1/ip/BD_tp1_rst_processing_system7_0_100M_0/BD_tp1_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_tp1_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==BD_tp1_rst_processing_system7_0_100M_0}]

# XDC: bd/BD_tp1/ip/BD_tp1_rst_processing_system7_0_100M_0/BD_tp1_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_tp1_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==BD_tp1_rst_processing_system7_0_100M_0}]

# XDC: bd/BD_tp1/ip/BD_tp1_rst_processing_system7_0_100M_0/BD_tp1_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/BD_tp1/ip/BD_tp1_auto_pc_0/BD_tp1_auto_pc_0_ooc.xdc

# XDC: bd/BD_tp1/BD_tp1_ooc.xdc
