# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -id {BD 41-1348}  -new_severity {INFO} 
set_msg_config  -id {BD 41-1343}  -new_severity {INFO} 
set_msg_config  -id {BD 41-1306}  -new_severity {INFO} 
set_msg_config  -id {IP_Flow 19-1687}  -new_severity {INFO} 
set_msg_config  -id {filemgmt 20-1763}  -new_severity {INFO} 
set_msg_config  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR} 
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir X:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.cache/wt [current_project]
set_property parent.project_path X:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.1 [current_project]
set_property ip_repo_paths x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/library [current_project]
add_files X:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/ipshared/analog.com/axi_hdmi_tx_v1_0/41b4d845/axi_hdmi_tx_constr.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_board.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/ipshared/analog.com/axi_spdif_tx_v1_0/c57c14c3/axi_spdif_tx_constr.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_axi_iic_fmc_0/system_axi_iic_fmc_0_board.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_axi_iic_fmc_0/system_axi_iic_fmc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all X:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files X:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib {
  X:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/adv7511_zed.srcs/sources_1/imports/hdl/system_wrapper.v
  x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/library/common/ad_iobuf.v
  x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/system_top.v
}
read_xdc x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/zed_system_constr.xdc
set_property used_in_implementation false [get_files x:/Bureau/A15/INF3995/tp2/tp2Code/tp2Code/zed_system_constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top system_top -part xc7z020clg484-1
write_checkpoint -noxdef system_top.dcp
catch { report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb }
