webtalk_init -webtalk_dir C:\\Users\\mazola\\Desktop\\Projet3\\tutoriel.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "mar. sept. 1 13:10:50 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "qd191p8snav1a4roo43kd6tf6j" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1441125677235" -context "sdk\\\\bsp/1441125677235"
webtalk_add_data -client sdk -key hwid -value "1441125429000" -context "sdk\\\\bsp/1441125677235"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1441125677235"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1441125677235"
webtalk_add_data -client sdk -key uid -value "1441125990475" -context "sdk\\\\application/1441125990475"
webtalk_add_data -client sdk -key hwid -value "1441125429000" -context "sdk\\\\application/1441125990475"
webtalk_add_data -client sdk -key bspid -value "1441125677235" -context "sdk\\\\application/1441125990475"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1441125990475"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1441125990475"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1441125990475"
webtalk_add_data -client sdk -key uid -value "1441126156429" -context "sdk\\\\application/1441126156429"
webtalk_add_data -client sdk -key hwid -value "1441125429000" -context "sdk\\\\application/1441126156429"
webtalk_add_data -client sdk -key bspid -value "1441125677235" -context "sdk\\\\application/1441126156429"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1441126156429"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1441126156429"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1441126156429"
webtalk_transmit -clientid 1768383199 -regid "" -xml C:\\Users\\mazola\\Desktop\\Projet3\\tutoriel.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\mazola\\Desktop\\Projet3\\tutoriel.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\mazola\\Desktop\\Projet3\\tutoriel.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
