# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/mazola/Desktop/Projet3/tutoriel.cache/wt [current_project]
set_property parent.project_path C:/Users/mazola/Desktop/Projet3/tutoriel.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files C:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/essai1.bd
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_axi_gpio_0_0/essai1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_axi_gpio_0_0/essai1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_axi_gpio_0_0/essai1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_axi_gpio_1_0/essai1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_axi_gpio_1_0/essai1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_axi_gpio_1_0/essai1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_blk_mem_gen_0_0/essai1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_xbar_0/essai1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_lmb_bram_if_cntlr_0_0/essai1_lmb_bram_if_cntlr_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_microblaze_0_0/essai1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_microblaze_0_0/essai1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_microblaze_0_0/essai1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_mdm_0_0/essai1_mdm_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_mdm_0_0/essai1_mdm_0_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_proc_sys_reset_0_0/essai1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_proc_sys_reset_0_0/essai1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/ip/essai1_proc_sys_reset_0_0/essai1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/essai1_ooc.xdc]
set_property is_locked true [get_files C:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/essai1.bd]

read_verilog -library xil_defaultlib C:/Users/mazola/Desktop/Projet3/tutoriel.srcs/sources_1/bd/essai1/hdl/essai1_wrapper.v
read_xdc C:/Users/mazola/Desktop/Projet3/tutoriel.srcs/constrs_1/new/mesContraintes.xdc
set_property used_in_implementation false [get_files C:/Users/mazola/Desktop/Projet3/tutoriel.srcs/constrs_1/new/mesContraintes.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top essai1_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef essai1_wrapper.dcp
catch { report_utilization -file essai1_wrapper_utilization_synth.rpt -pb essai1_wrapper_utilization_synth.pb }
