set_property SRC_FILE_INFO {cfile:c:/Users/mazola/Desktop/Projet3/tp1.srcs/sources_1/bd/BD_tp1/ip/BD_tp1_processing_system7_0_0/BD_tp1_processing_system7_0_0.xdc rfile:../../../tp1.srcs/sources_1/bd/BD_tp1/ip/BD_tp1_processing_system7_0_0/BD_tp1_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:BD_tp1_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/mazola/Desktop/Projet3/tp1.srcs/constrs_1/new/contraintsTP1.xdc rfile:../../../tp1.srcs/constrs_1/new/contraintsTP1.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports sys_clock]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10 [get_ports sys_clock]
